{% set version = "1.2.0" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: a1530cd973daa7bd3621a0d720fa790d20709012987367eca119802eeac83055

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - gridio = gridgeo.gridio:main

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netcdf4
    - shapely
    - docopt

test:
  imports:
    - gridgeo
  commands:
    - gridio -h

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats.'

extra:
  recipe-maintainers:
    - ocefpaf
