{% set version = "1.0.0" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/pyoceans/gridgeo/archive/v{{ version }}.tar.gz
  sha256: b648485284ad31229553f779069f0be2a68d562b9768c4fdd13081da18ad0c9a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyugrid
    - pysgrid
    - shapely
    - fiona

test:
  imports:
    - gridgeo

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats.'

extra:
  recipe-maintainers:
    - ocefpaf
