{% set version = "1.5.2" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: 07da02062558d76f565b766fe71f3b46aa3bd3a65fb5579a8140cc8052afeff8

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gridio = gridgeo.gridio:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - netcdf4
    - shapely
    - docopt

test:
  requires:
    - python {{ python_min }}
  imports:
    - gridgeo
  commands:
    - gridio -h

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats'

extra:
  recipe-maintainers:
    - ocefpaf
