{% set version = "1.5.0" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: 21082025d1b9c67be9725dd5cf2b427deffedb3719a5e201365a9a8e93de525d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gridio = gridgeo.gridio:main

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netcdf4
    - shapely
    - docopt

test:
  imports:
    - gridgeo
  commands:
    - gridio -h

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats'

extra:
  recipe-maintainers:
    - ocefpaf
