{% set python_min = "3.10" %}
{% set version = "1.6.0" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: 05cab9c7aeaa36dd387261183826bc95a0289fa6b4af9a7e1d6c37ae6aea0320

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - gridio = gridgeo.gridio:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - netcdf4
    - shapely
    - docopt

test:
  requires:
    - python {{ python_min }}
  imports:
    - gridgeo
  commands:
    - gridio -h

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats'

extra:
  recipe-maintainers:
    - ocefpaf
