{% set version = "1.0.1" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: 107c9068115116b952213a3236444718b0eec52db30f01c023cb1742cd26c8d4

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netcdf4
    - shapely

test:
  imports:
    - gridgeo

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats.'

extra:
  recipe-maintainers:
    - ocefpaf
