{% set version = "1.5.1" %}

package:
  name: gridgeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gridgeo/gridgeo-{{ version }}.tar.gz
  sha256: 41ee8fba172a8992afde402563d8b87e0a9e698664baccfdd6f894fa5e223f7e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gridio = gridgeo.gridio:main

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netcdf4
    - shapely
    - docopt

test:
  imports:
    - gridgeo
  commands:
    - gridio -h

about:
  home: https://github.com/pyoceans/gridgeo
  license: MIT
  license_file: LICENSE.txt
  summary: 'Quick grid visualization and conversion to GIS formats'

extra:
  recipe-maintainers:
    - ocefpaf
