travis:
  secure:
    BINSTAR_TOKEN: OcH3DAix3UAoWNtUZAHCxQzmgWTZMSCarhiw9kaj6lLLLCKxyMM+yMQotfSLCftPPtimtOKlrtMxmpi2hyl7B3/crXViB0aLrLKGswReXsTVdj2FcLLRYnfqUtJovAIq5KCseri83GSeEdGuRMcYhXFHH1ZgTrgtxC9ja+T8+by3umI3zUSpDiiunKd8jhFQJU7Yt24cDqHUdeGF8UXXLn57GQZfkjCYXJad+llwEADsiCmFgC3B0A0vUn9J54oifJpjRf8aETBiS/QJwZ/pQjTtMZRwI6e42a9kSsWdLhkCY+YWfkfjxdmBSY8pZz7PAI7zJur5m9R3BKVc3swZiZhwqBqsIXfIvPfNWSf+/bGh7F3GKg8KPS59I1dNEzvtgMjiILTmksx62WBB8VofVCweMWwCjdEdqelf39bHn5SAV7jp94y19UZzqdC9cj5zn6dCneI0t1yFJdTtWjGn3Q4YY2c8DQD7rTPpFdozXzx6LQLy/+OGrRDU0EQ/XhOHNBotXy3vdOxlOh3+VJ4YLQAGcNgGYHZAsHmlXW/pTwjsbr+uM9Uvt7Bb3Lurv7cfJNSv92o5GJwJcmZPx+Gegl/Kts4BwGsVouMMjW+dck8Ic20gXo6JTmou7qH6nZlIX1qX725rY24Gd6WGur0TZfRX98937THjqnYOUGvp03w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
